DROP TABLE IF EXISTS Employees;
DROP TABLE IF EXISTS Roles;

DROP TABLE IF EXISTS Deliveries;
DROP TABLE IF EXISTS Drivers;

DROP TABLE IF EXISTS Orders;
DROP TABLE IF EXISTS Storage;

DROP TABLE IF EXISTS Clients;
DROP TABLE IF EXISTS Products;
DROP TABLE IF EXISTS Payments;